env: "local" # local, dev, prod
storage_path: "postgres://myuser:password123@db:5432/myapp?sslmode=disable"# localhost for local, db for docker
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s